#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2018, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

source $(dirname $0)/../../etc/vmm/kvm/kvmrc
source $(dirname $0)/../../scripts_common.sh

domain=$1

mkdir -p `dirname $domain`
cat > $domain

# activate LVM devices 
DST_PATH=$(dirname "${domain}")
for disk in $(ls ${DST_PATH}/disk.*); do
    DEVICE=$(readlink "${disk}" 2>/dev/null)

    # disk symlink resolves and target file/device doesn't
    # exist yet, but lvs knows about it -> activate
    if [ -n "${DEVICE}" ] && ! [ -e "${DEVICE}" ]; then
        if ${SUDO} ${LVS} "${DEVICE}" >/dev/null 2>&1; then
            ${SUDO} ${LVCHANGE} -ay "${DEVICE}" >/dev/null

            if [ $? -ne 0 ]; then
                error_message "Failed to activate LVM device ${DEVICE}"
                exit -1
            fi
        fi
    fi
done

data=`virsh --connect $LIBVIRT_URI create $domain`

if [ "x$?" = "x0" ]; then
    echo $data | sed 's/Domain //' | sed 's/ created from .*$//'
else
    error_message "Could not create domain from $domain"
    exit -1
fi
